# Generated by Django 4.0.6 on 2023-04-24 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='token',
            new_name='forget_password_token',
        ),
    ]
