# Generated by Django 4.0.6 on 2023-04-24 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='forget_password_token',
            new_name='token',
        ),
    ]
